## Single neuron

In [1]:
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2

In [3]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2] +bias
print(output)

2.3


** Adding an input **

In [4]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

In [5]:
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3] +bias
print(output)

4.8


## Layer of Neuron 

In [1]:
inputs = [1,2,3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

In [2]:
outputs = [
    # first neuron
    inputs[0] * weights1[0]+
    inputs[1] * weights1[1]+
    inputs[2] * weights1[2]+
    inputs[3] * weights1[3]+ bias1 ,

    # second
    inputs[0] * weights2[0]+
    inputs[1] * weights2[1]+
    inputs[2] * weights2[2]+
    inputs[3] * weights2[3]+ bias2,

    # third neuron
    inputs[0] * weights3[0]+
    inputs[1] * weights3[1]+
    inputs[2] * weights3[2]+
    inputs[3] * weights3[3]+ bias3
    
]

In [3]:
print(outputs)

[4.8, 1.21, 2.385]


** Calculating through loops **

In [11]:
inputs = [1,2,3, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2,3,0.5]

In [12]:
layers_output = []

In [13]:
# for each neuron
for neuron_weights , neuron_bias in zip(weights,biases):
    # setting a variable
    neuron_output = 0
    # for each input and weight
    for n_input , weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight

    neuron_output += neuron_bias

    layers_output.append(neuron_output)

print(layers_output)

[4.8, 1.21, 2.385]


** Dot product 2 Vectors **

In [15]:
import numpy as np

In [16]:
a = [1,2,3]
b = [2,3,4]

In [17]:
np.dot(a,b)

np.int64(20)

In [19]:
a[0]*b[0]+a[1]*b[1]+a[2]*b[2]

20

#### Single layer with numpy

In [1]:
import numpy as np

In [6]:
inputs = [1.0,2.0,3.0,2.5]
weights = [
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
biases = [2.0,3.0,0.5]

In [7]:
layerOutput = np.dot(weights,inputs) + biases

In [8]:
print(layerOutput)

[4.8   1.21  2.385]


** Checking layer individualy **

In [9]:
np.dot(weights[0],inputs)+ biases[0]

np.float64(4.8)

In [10]:
np.dot(weights[1],inputs) + biases[1]

np.float64(1.2099999999999997)

In [11]:
np.dot(weights[2],inputs)+ biases[2]

np.float64(2.385)

 ** Multiplication by transpose **

In [12]:
a = np.array([1,2,3])
b = np.array([2,3,4])

In [13]:
np.dot(a,b.T)

np.int64(20)

** Layers of neurons and batch of data **

In [28]:
inputs = [
    [1.0,2.0,3.0,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5,2.7,3.3,-0.8]
]
weights1 = [
    [0.2,0.8,-0.5,1],
    [0.5,-0.91,0.26,-0.5],
    [-0.26,-0.27,0.17,0.87]
]
biases1 = [2.0,3.0,0.5]

In [31]:
output = np.dot(inputs,np.array(weights).T) + biases1

In [32]:
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

** Adding Layers **

In [35]:
weights2 = [
    [0.1,-0.14,0.5],
    [-0.5,0.12,-0.33],
    [-0.44,0.73,-0.13]
]
biases2 = [-1,2,0.5]

In [36]:
layer1Output = np.dot(inputs,np.array(weights1).T) + biases1
layer2Output = np.dot(layer1Output,np.array(weights2).T) + biases2 

In [37]:
layer2Output 

array([[ 0.5031 , -1.04185, -1.03875],
       [ 0.2434 , -2.7332 , -4.7633 ],
       [-0.99314,  1.41254,  0.64345]])

In [39]:
np.array([
    [1,-1,-1],
    [1,-1,-1],
    [-1,1,1]
])

array([[ 1, -1, -1],
       [ 1, -1, -1],
       [-1,  1,  1]])