#### Install numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [3]:
numList = [5,1,3]

In [15]:
floatList = [3.1,7.7,8.9]

In [5]:
textList = ['ujwal','saransh','sahil']

In [6]:
boolList = [True,False,True]

In [7]:
np.array(numList)

array([5, 1, 3])

In [8]:
npArr = np.array(numList)

In [10]:
print(npArr)

[5 1 3]


In [11]:
npArr

array([5, 1, 3])

In [16]:
np.array(floatList)

array([3.1, 7.7, 8.9])

In [17]:
floatArr = np.array(floatList)

In [19]:
floatArr.dtype

dtype('float64')

In [18]:
print(floatArr)

[3.1 7.7 8.9]


In [21]:
np.array(boolList)

array([ True, False,  True])

In [23]:
boolArr = np.array(boolList)

In [24]:
boolArr

array([ True, False,  True])

In [25]:
boolArr.dtype

dtype('bool')

In [26]:
print(boolArr)

[ True False  True]


In [29]:
np.array([5,6.3,True,"Ujwal"])

array(['5', '6.3', 'True', 'Ujwal'], dtype='<U32')

In [4]:
numList =  [2,3,4,5,6,7,8,90,23,45]

In [5]:
np.array(numList)

array([ 2,  3,  4,  5,  6,  7,  8, 90, 23, 45])

In [18]:
Arr = np.array(numList)

In [19]:
Arr

array([ 2,  3,  4,  5,  6,  7,  8, 90, 23, 45])

In [20]:
print(numList)

[2, 3, 4, 5, 6, 7, 8, 90, 23, 45]


In [21]:
Arr.ndim

1

In [23]:
Arr.size

10

#### Scaler

In [54]:
scaler = np.array(5)

In [55]:
scaler

array(5)

In [56]:
print(scaler)

5


In [57]:
scaler.dtype

dtype('int64')

In [58]:
scaler.shape

()

In [59]:
scaler.size

1

In [60]:
scaler.ndim

0

#### Vector

#### Matrix

In [4]:
matrix = np.array(
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ]  
)
print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
matrix.ndim

2

In [8]:
matrix.shape

(3, 4)

In [9]:
matrix.dtype

dtype('int64')

#### Tensor

In [22]:
tensor = np.array([
[
    [1,2],
    [3,4]
],
[
    [5,6],
    [7,8] 
],
[
    [9,10],
    [11,12]
]
       ])

In [23]:
tensor.ndim

3

In [24]:
tensor.shape

(3, 2, 2)

In [25]:
tensor.dtype

dtype('int64')

In [26]:
tensor.size

12

#### Reshape 

In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [28]:
arr.dtype

dtype('int64')

In [29]:
arr.shape

(12,)

In [30]:
arr.size

12

In [31]:
arr.ndim

1

In [32]:
arr.reshape(1,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [33]:
arr.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [36]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [37]:
arr.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [39]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
[x for x in range(1,25)]

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [5]:
arr.reshape(4,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [6]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [7]:
arr.reshape(3,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])