In [1]:
import numpy as np

In [4]:
np.random.seed(100)

** Indexing **

In [5]:
np.random.randint(1,100,(5,3,2))

array([[[ 9, 25],
        [68, 88],
        [80, 49]],

       [[11, 95],
        [53, 99],
        [54, 67]],

       [[99, 15],
        [35, 25],
        [16, 61]],

       [[59, 17],
        [10, 94],
        [87,  3]],

       [[28,  5],
        [32,  2],
        [14, 84]]], dtype=int32)

In [6]:
arr = np.random.randint(1,100,(5,3,2))

In [7]:
arr

array([[[ 5, 92],
        [60, 68],
        [ 8, 50]],

       [[48, 66],
        [62, 15],
        [56, 72]],

       [[81,  3],
        [95, 20],
        [99, 64]],

       [[54, 28],
        [57, 31],
        [49, 48]],

       [[40, 39],
        [45, 19],
        [65, 57]]], dtype=int32)

In [8]:
arr[2]

array([[81,  3],
       [95, 20],
       [99, 64]], dtype=int32)

In [9]:
arr[2][1]

array([95, 20], dtype=int32)

In [10]:
arr[2][1] = 22,23

In [11]:
arr

array([[[ 5, 92],
        [60, 68],
        [ 8, 50]],

       [[48, 66],
        [62, 15],
        [56, 72]],

       [[81,  3],
        [22, 23],
        [99, 64]],

       [[54, 28],
        [57, 31],
        [49, 48]],

       [[40, 39],
        [45, 19],
        [65, 57]]], dtype=int32)

In [15]:
arr[2][1][0]

np.int32(22)

** Slicing ** 

In [16]:
arr = np.random.randint(1,50,(5,4,3))

In [17]:
arr

array([[[35, 11, 18],
        [ 9, 14, 43],
        [31, 18,  5],
        [41, 28, 28]],

       [[20, 15,  1],
        [14, 13, 43],
        [ 4,  7,  4],
        [21, 16, 11]],

       [[24, 48,  4],
        [42, 49, 44],
        [37,  6,  8],
        [39, 23, 31]],

       [[35, 43, 21],
        [32, 46, 13],
        [34, 39, 43],
        [23,  1, 35]],

       [[20,  5,  5],
        [36, 24, 10],
        [49, 49, 22],
        [26,  7, 38]]], dtype=int32)

In [18]:
arr[3]

array([[35, 43, 21],
       [32, 46, 13],
       [34, 39, 43],
       [23,  1, 35]], dtype=int32)

In [26]:
arr[3][2:4]

array([[34, 39, 43],
       [23,  1, 35]], dtype=int32)

In [31]:
arr[3][2:4,0:2]

array([[34, 39],
       [23,  1]], dtype=int32)

In [33]:
arr = np.random.randint(1,100,(7,6,5))

In [34]:
arr

array([[[59, 40, 95, 52, 31],
        [67, 25, 56, 18, 46],
        [90, 46, 36, 17, 13],
        [87, 83, 68, 93, 96],
        [21, 11,  9, 90, 73],
        [31, 13, 19, 94, 93]],

       [[45, 58,  1, 74, 55],
        [93, 67, 17,  6, 52],
        [91, 35, 68, 95, 79],
        [55, 78, 85,  2, 15],
        [34, 21, 41, 25, 94],
        [59, 29, 83, 83,  8]],

       [[95,  3, 64,  3, 88],
        [18, 91, 94, 97, 75],
        [54, 31, 68, 29, 38],
        [83, 18, 11, 14, 82],
        [26, 67, 16, 12, 39],
        [23, 56, 58, 88, 52]],

       [[49, 54, 18, 66, 43],
        [94, 45, 17, 52, 55],
        [56, 84, 43, 62, 38],
        [81,  3, 63, 82, 17],
        [71, 54, 99, 97, 48],
        [49, 10, 50, 54, 35]],

       [[ 4, 12, 50, 30, 37],
        [94, 68, 27, 53, 37],
        [74, 32, 86, 93, 69],
        [84, 72, 62, 94, 37],
        [43, 14, 49, 83, 33],
        [39, 41, 54, 94, 15]],

       [[39, 87, 38,  1, 60],
        [42, 45, 20, 77, 67],
        [14, 88, 66, 69, 55],


In [36]:
arr[3]

array([[49, 54, 18, 66, 43],
       [94, 45, 17, 52, 55],
       [56, 84, 43, 62, 38],
       [81,  3, 63, 82, 17],
       [71, 54, 99, 97, 48],
       [49, 10, 50, 54, 35]], dtype=int32)

In [37]:
arr[3][2:4]

array([[56, 84, 43, 62, 38],
       [81,  3, 63, 82, 17]], dtype=int32)

In [42]:
arr[3][2:4,0:2]

array([[56, 84],
       [81,  3]], dtype=int32)

In [44]:
arr[3][2:4,0:2][1]

array([81,  3], dtype=int32)

In [45]:
arr[3][2:4,0:2][1] = 7,7

In [46]:
arr

array([[[59, 40, 95, 52, 31],
        [67, 25, 56, 18, 46],
        [90, 46, 36, 17, 13],
        [87, 83, 68, 93, 96],
        [21, 11,  9, 90, 73],
        [31, 13, 19, 94, 93]],

       [[45, 58,  1, 74, 55],
        [93, 67, 17,  6, 52],
        [91, 35, 68, 95, 79],
        [55, 78, 85,  2, 15],
        [34, 21, 41, 25, 94],
        [59, 29, 83, 83,  8]],

       [[95,  3, 64,  3, 88],
        [18, 91, 94, 97, 75],
        [54, 31, 68, 29, 38],
        [83, 18, 11, 14, 82],
        [26, 67, 16, 12, 39],
        [23, 56, 58, 88, 52]],

       [[49, 54, 18, 66, 43],
        [94, 45, 17, 52, 55],
        [56, 84, 43, 62, 38],
        [ 7,  7, 63, 82, 17],
        [71, 54, 99, 97, 48],
        [49, 10, 50, 54, 35]],

       [[ 4, 12, 50, 30, 37],
        [94, 68, 27, 53, 37],
        [74, 32, 86, 93, 69],
        [84, 72, 62, 94, 37],
        [43, 14, 49, 83, 33],
        [39, 41, 54, 94, 15]],

       [[39, 87, 38,  1, 60],
        [42, 45, 20, 77, 67],
        [14, 88, 66, 69, 55],


In [47]:
arr[3][2:4,0:2]

array([[56, 84],
       [ 7,  7]], dtype=int32)

In [52]:
arr[3][2:4,0:2] = 5,5

In [53]:
arr

array([[[59, 40, 95, 52, 31],
        [67, 25, 56, 18, 46],
        [90, 46, 36, 17, 13],
        [87, 83, 68, 93, 96],
        [21, 11,  9, 90, 73],
        [31, 13, 19, 94, 93]],

       [[45, 58,  1, 74, 55],
        [93, 67, 17,  6, 52],
        [91, 35, 68, 95, 79],
        [55, 78, 85,  2, 15],
        [34, 21, 41, 25, 94],
        [59, 29, 83, 83,  8]],

       [[95,  3, 64,  3, 88],
        [18, 91, 94, 97, 75],
        [54, 31, 68, 29, 38],
        [83, 18, 11, 14, 82],
        [26, 67, 16, 12, 39],
        [23, 56, 58, 88, 52]],

       [[49, 54, 18, 66, 43],
        [94, 45, 17, 52, 55],
        [ 5,  5, 43, 62, 38],
        [ 5,  5, 63, 82, 17],
        [71, 54, 99, 97, 48],
        [49, 10, 50, 54, 35]],

       [[ 4, 12, 50, 30, 37],
        [94, 68, 27, 53, 37],
        [74, 32, 86, 93, 69],
        [84, 72, 62, 94, 37],
        [43, 14, 49, 83, 33],
        [39, 41, 54, 94, 15]],

       [[39, 87, 38,  1, 60],
        [42, 45, 20, 77, 67],
        [14, 88, 66, 69, 55],


In [74]:
a = np.arange(10)

In [75]:
a = a.reshape(2,5)

In [76]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [79]:
a = b

In [80]:
b = a.copy()

In [81]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [84]:
b[1][2] = 3

In [85]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 3, 8, 9]])

In [86]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
zeros =  np.zeros((5,5))

In [94]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [95]:
one = np.ones((5,5))

In [96]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])