In [1]:
import numpy as np

In [2]:
numList = ([1,2,3,4,5],[6,7,8,9,10])

In [3]:
np.array(numList)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [4]:
npArr = np.array(numList)

In [5]:
print(npArr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
npArr.shape

(2, 5)

In [7]:
npArr.dtype

dtype('int64')

In [8]:
npArr.size

10

** Zeros**

In [9]:
zeros = np.zeros((1,5))

In [10]:
zeros

array([[0., 0., 0., 0., 0.]])

In [11]:
zeros.shape

(1, 5)

In [12]:
zeros.ndim

2

** Range **

In [13]:
rng = np.arange(21)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
rng.ndim

1

In [16]:
rng.size

21

In [17]:
rng.shape

(21,)

** Linspace**

In [18]:
lin = np.linspace(1,5,5)  # yeh function ek se dusre no k bich meh numbers provide krta hea jesa hum chaiye

In [19]:
lin  # this function has 3 no and only one ()

array([1., 2., 3., 4., 5.])

In [20]:
lin.shape

(5,)

In [21]:
lin.size

5

In [22]:
lin.dtype

dtype('float64')

In [23]:
lin.ndim

1

** Empty **

In [24]:
emp = np.empty((7,6))

In [25]:
emp

array([[0.00000000e+000, 8.32786531e-312, 0.00000000e+000,
        0.00000000e+000, 4.94065646e-324, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 4.94065646e-324,
        0.00000000e+000, 6.95183846e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [26]:
emp.ndim

2

In [27]:
emp_like = np.empty

In [28]:
emp_like

<function numpy.empty>

** Identity **

In [29]:
id = np.identity(45)

In [30]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
id.size

2025

In [32]:
id.ndim

2

In [33]:
id.shape

(45, 45)

** Reshape/ Ravel**

In [7]:
arr = np.arange(60)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [9]:
arr.reshape(4,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [10]:
arr = arr.reshape(4,15)

In [11]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [13]:
arr = arr.ravel()

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [15]:
arr.shape

(60,)

In [17]:
x = ([[1,2,3],[4,5,6],[7,0,1]])

In [18]:
arr = np.array(x)

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 0, 1]])

In [20]:
arr.sum(axis=0)

array([12,  7, 10])

In [21]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [23]:
arr.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [24]:
arr.T

array([[1, 4, 7],
       [2, 5, 0],
       [3, 6, 1]])

In [27]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
0
1


In [34]:
one =np.array([1,2,3333,55,7])

In [36]:
one

array([   1,    2, 3333,   55,    7])

In [38]:
one.argmax()

np.int64(2)

In [39]:
one.argmin()

np.int64(0)

In [40]:
one.argsort()

array([0, 1, 4, 3, 2])

In [41]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [42]:
arr.argmax()

np.int64(8)

In [43]:
arr.argmin()

np.int64(0)

In [44]:
arr.argmax(axis=0)

array([2, 2, 2])

In [46]:
arr.argmax(axis=1)

array([2, 2, 2])

In [49]:
arr.argmin(axis=0)

array([0, 0, 0])

In [50]:
arr.argmin(axis=1)

array([0, 0, 0])