In [1]:
import numpy as np

### Basic operation

In [60]:
np.mean(arr)  # average

np.float64(1.0)

In [59]:
np.sum(arr)  # combine total of all array

np.int64(9)

In [61]:
np.median(arr)  # The median is the middle value when the numbers are arranged in order

np.float64(1.0)

In [62]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [63]:
np.argmax(arr)    # maximun number in which position

np.int64(5)

In [64]:
np.argmin(arr)   # minimun number in which position 

np.int64(2)

In [65]:
np.argsort(arr)   # make easiest way to solve a array or equation

array([[2, 0, 1],
       [1, 0, 2],
       [2, 0, 1]])

### Broadcasting 

In [2]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr = np.arange(0,9)
arr = arr.reshape(3,3)

In [4]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [6]:
arr = arr + 1

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [9]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr = np.arange(1,10)
arr = arr.reshape(3,3)

In [11]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
a = arr

In [13]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Dot product on 2 vectors

In [14]:
a = np.array([5,-3,2])
b = np.array([4,5,3])

In [15]:
a

array([ 5, -3,  2])

In [16]:
b

array([4, 5, 3])

In [17]:
a.dot(b)     # Used to multiply two arrays, especially for matrix multiplication

np.int64(11)

In [18]:
b.dot(a)

np.int64(11)

#### Cross product 2 vectors

In [19]:
a = np.array([3,4,5])
b = np.array([7,8,9])

In [20]:
a

array([3, 4, 5])

In [21]:
b

array([7, 8, 9])

In [22]:
np.cross(a,b)

array([-4,  8, -4])

In [23]:
c = np.cross(a,b)

In [24]:
c.dot(a)

np.int64(0)

In [25]:
c.dot(b)

np.int64(0)

### Determinant

In [26]:
arr = np.array([
    [3,5,2],
    [1,4,7],
    [6,8,9]
])

In [27]:
np.linalg.det(arr)

np.float64(72.99999999999999)

In [28]:
round(np.linalg.det(arr))

73

In [29]:
arr = np.array([
    [3,5,2],
    [6,10,4],
    [6,8,9]
])

In [30]:
np.linalg.det(arr)   # linalg stands for "Linear Algebra" 1.Finding matrix inverse 2.Calculating the determinant 3.Solving systems of linear equations

np.float64(0.0)

In [31]:
round(np.linalg.det(arr))

0

### Inverse of a Matrix

In [32]:
arr =np.array([
    [1,2,3],
    [3,-2,1],
    [4,1,1]
])

In [33]:
inv = np.linalg.inv(arr)

In [34]:
inv

array([[-0.09375,  0.03125,  0.25   ],
       [ 0.03125, -0.34375,  0.25   ],
       [ 0.34375,  0.21875, -0.25   ]])

In [36]:
arr.dot(inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.linalg.det(arr)

np.float64(32.000000000000014)

In [38]:
i = np.eye(3)   # All the diagonal elements are 1 and All the off-diagonal elements are 0

In [39]:
np.linalg.det(i)  # Used to calculate the determinant of a square matrix

np.float64(1.0)

In [40]:
arr

array([[ 1,  2,  3],
       [ 3, -2,  1],
       [ 4,  1,  1]])

In [41]:
arr.dot(i)

array([[ 1.,  2.,  3.],
       [ 3., -2.,  1.],
       [ 4.,  1.,  1.]])

### Multiplication of 2 Matrix

In [42]:
arr = np.random.randint(1,10,(3,3))

In [43]:
arr

array([[7, 4, 3],
       [2, 1, 2],
       [4, 5, 7]], dtype=int32)

In [44]:
x = np.random.randint(arr)

In [45]:
y = np.random.randint(1,10,(3,3))

In [46]:
y

array([[6, 4, 6],
       [6, 6, 2],
       [8, 3, 4]], dtype=int32)

In [47]:
x.dot(y)

array([[30, 22, 26],
       [ 6,  4,  6],
       [40, 26, 24]], dtype=int32)

In [71]:
arr = np.random.randint(1,3,(2,2))

In [72]:
arr

array([[1, 2],
       [2, 2]], dtype=int32)

In [73]:
brr = np.random.randint(4,5,(2,2))

In [74]:
brr

array([[4, 4],
       [4, 4]], dtype=int32)

In [75]:
arr.dot(brr)

array([[12, 12],
       [16, 16]], dtype=int32)

### Solving linear algebra

In [48]:
arr = np.array([
    [1,3,-2],
    [2,-1,6],
    [1,1,-2]
])

In [49]:
C = np.array([10,3,5])

In [50]:
inv = np.linalg.inv(arr)

In [51]:
inv

array([[-2.00000000e-01,  2.00000000e-01,  8.00000000e-01],
       [ 5.00000000e-01, -1.58603289e-17, -5.00000000e-01],
       [ 1.50000000e-01,  1.00000000e-01, -3.50000000e-01]])

In [52]:
inv.dot(C)

array([2.6 , 2.5 , 0.05])

### Eigen Values Eigen vector

In [ ]:
# 1.Eigenvectors: Special directions that don't rotate under transformation
# 2.Eigenvalues: How much those vectors get stretched or shrunk

In [53]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])

In [54]:
a,b = np.linalg.eig(arr)

In [55]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([ 3.25878567, -1.74822811, -3.51055757]), eigenvectors=array([[-0.68032035, -0.68273056,  0.58984922],
       [-0.685363  ,  0.71750056, -0.79590801],
       [-0.25969557,  0.13810117,  0.13641241]]))

In [56]:
a

array([ 3.25878567, -1.74822811, -3.51055757])

In [57]:
b

array([[-0.68032035, -0.68273056,  0.58984922],
       [-0.685363  ,  0.71750056, -0.79590801],
       [-0.25969557,  0.13810117,  0.13641241]])

In [58]:
arr

array([[ 1,  3, -2],
       [ 2, -1,  6],
       [ 1,  1, -2]])